replicaCount: 1
image:
  # repository: # Custom repository if neeed TODO:
  name: sohlman/lifekube
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20201012"
  debug: true
  spring:
    profiles: generic
#
# Environmental variables for the Liferay container
# 
environmentalVariables:
  LIFERAY_JAVA_OPTS: -Xms3g -Xmx3g
  LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE: 0.0.0.0:11311
  LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE: domain
tomcat:
  redis:
    enabled: true
liferay:
  S3:
    enabled: true
    bucketName: liferay
    accessKey: liferaySecret
    secretKey: liferayPassword
    s3Endpoint:
      name:
      nameSpace:
  elastic:
    enabled: true
  configmaps:
  - name:
    toPath:
minio:
  persistence:
    size: 10Gi
  accessKey: liferaySecret
  secretKey: liferayPassword
  ingress:
    enabled: false
  buckets:
  - name: liferay
    policy: none
    purge: false
elastic:
  clusterName: LiferayElasticsearchCluster
  volumeClaimTemplate:
    resources:
      requests:
        storage: 10Gi
mysql:
  mysqlRootPassword: admin
  initializationFiles:
    first-db.sql: |-
      CREATE DATABASE IF NOT EXISTS lportal DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
  persistence:
    size: 10Gi
redis:
  password: asdQWE123@@@
