apiVersion: v1
data:
  configure.sh: |+
    \cp -Rf /liferayconfigs/osgi/configs/* /opt/liferay/osgi/configs/
    \cp -Rf /liferayconfigs/tomcat/conf/* /opt/liferay/tomcat/conf/
    \cp -Rf /liferayconfigs/tomcat/lib/* /opt/liferay/tomcat/lib/
    \cp -f /liferayconfigs/portal-ext.properties /opt/liferay/
    \cp -f /liferayconfigs/jgroups-*.xml /opt/liferay/  
    {{- if (  .Values.liferay.S3.enabled ) }}
    \cp -f /liferaydefault/S3/com.liferay.portal.store.s3.configuration.S3StoreConfiguration.config /opt/liferay/osgi/configs/com.liferay.portal.store.s3.configuration.S3StoreConfiguration.config
    cat /liferaydefault/S3/portal-ext.properties >> /opt/liferay/portal-ext.properties
    {{- end }}
    {{- if (  .Values.liferay.elastic.enabled ) }}
    \cp -f /liferaydefault/elastic/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config /opt/liferay/osgi/configs/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config
    {{- end }}
    \cp -Rf /lifekube/* /opt/liferay/

    chown -R liferay:liferay /opt/liferay

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-liferay-scripts