apiVersion: v1
data:
  tomcat-server.xml: |+
    <?xml version="1.0" encoding="UTF-8"?>
    <Server port="8005" shutdown="SHUTDOWN">
    <GlobalNamingResources>
    <Resource auth="Container" description="User database that can be updated and saved" factory="org.apache.catalina.users.MemoryUserDatabaseFactory" name="UserDatabase" pathname="conf/tomcat-users.xml" type="org.apache.catalina.UserDatabase"/>
    </GlobalNamingResources>
    <Listener className="org.apache.catalina.startup.VersionLoggerListener"/>
    <Listener SSLEngine="on" className="org.apache.catalina.core.AprLifecycleListener"/>
    <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener"/>
    <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener"/>
    <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener"/>
    <Service name="Catalina">
    <Connector URIEncoding="UTF-8" connectionTimeout="20000" executor="tomcatThreadPool" port="8080" protocol="HTTP/1.1" redirectPort="8443" scheme="https" secure="true"/>
    <Connector URIEncoding="UTF-8" connectionTimeout="20000" executor="tomcatThreadPool" port="8081" protocol="HTTP/1.1" redirectPort="8443"/>
    <Engine defaultHost="localhost" name="Catalina">
    <Host appBase="webapps" autoDeploy="true" name="localhost" unpackWARs="true"/>
    <Realm className="org.apache.catalina.realm.LockOutRealm">
    <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
    </Realm>
    </Engine>
    <Executor maxThreads="150" minSpareThreads="4" name="tomcatThreadPool" namePrefix="catalina-exec-"/>
    </Service>
    </Server>
  tomcat-context.xml: |+
    <?xml version="1.0" encoding="UTF-8"?>
    <Context>
      <WatchedResource>WEB-INF/web.xml</WatchedResource>
      <WatchedResource>WEB-INF/tomcat-web.xml</WatchedResource>
      <WatchedResource>${catalina.base}/conf/web.xml</WatchedResource>
      <Manager className="com.liferay.redis.redisson.integration.tomcat.LiferayRedissonSessionManager" configPath="${catalina.base}/conf/redisson.conf" readMode="REDIS" updateMode="DEFAULT"/>
    </Context>
  tomcat-redisson.conf: |+
    {
      "singleServerConfig":{
        "address": "redis://{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379"
      },
      "threads":0,
      "nettyThreads":0,
      "transportMode":"NIO",
      "codec":{
        "class":"com.liferay.redis.tomcat.client.redisson.codec.FstLiferayCodec"
      }
    }
  jgroups-jdbc.xml: |+
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="urn:org:jgroups"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
        <TCP bind_port="7800"
             recv_buf_size="${tcp.recv_buf_size:130k}"
             send_buf_size="${tcp.send_buf_size:130k}"
             max_bundle_size="64K"
             sock_conn_timeout="300"
             thread_pool.min_threads="0"
             thread_pool.max_threads="20"
             thread_pool.keep_alive_time="30000"/>
        <JDBC_PING  connection_url="jdbc:mysql://{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local/lportal?characterEncoding=UTF-8"
             connection_username="root"
             connection_password="admin"
             connection_driver="com.mysql.cj.jdbc.Driver" />
        <MERGE3  min_interval="10000"
                 max_interval="30000"/>
        <FD_SOCK/>
        <FD_ALL timeout="9000" interval="3000" />
        <VERIFY_SUSPECT timeout="1500"  />
        <BARRIER />
        <pbcast.NAKACK2 use_mcast_xmit="false"
                       discard_delivered_msgs="true"/>
        <UNICAST3 />
        <pbcast.STABLE desired_avg_gossip="50000"
                       max_bytes="4M"/>
        <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
        <UFC max_credits="2M"
             min_threshold="0.4"/>
        <MFC max_credits="2M"
             min_threshold="0.4"/>
        <FRAG2 frag_size="60K"  />
        <!--RSVP resend_interval="2000" timeout="10000"/-->
        <pbcast.STATE_TRANSFER/>
    </config>
  jgroups-kubernetes.xml: |+
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="urn:org:jgroups"
            xsi:schemaLocation="urn:org:jgroups http://www.jgroups.org/schema/jgroups.xsd">
        <TCP bind_port="7800"
             recv_buf_size="${tcp.recv_buf_size:130k}"
             send_buf_size="${tcp.send_buf_size:130k}"
             max_bundle_size="64K"
             sock_conn_timeout="300"
             thread_pool.min_threads="0"
             thread_pool.max_threads="20"
             thread_pool.keep_alive_time="30000"/>
        <org.jgroups.protocols.kubernetes.KUBE_PING
              port_range="1"
             namespace="${KUBERNETES_NAMESPACE:{{ .Release.Namespace }}}"
             labels="${KUBERNETES_LABELS:type=portal}" />
        <MERGE3  min_interval="10000"
                 max_interval="30000"/>
        <FD_SOCK/>
        <FD_ALL timeout="9000" interval="3000" />
        <VERIFY_SUSPECT timeout="1500"  />
        <BARRIER />
        <pbcast.NAKACK2 use_mcast_xmit="false"
                       discard_delivered_msgs="true"/>
        <UNICAST3 />
        <pbcast.STABLE desired_avg_gossip="50000"
                       max_bytes="4M"/>
        <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
        <UFC max_credits="2M"
             min_threshold="0.4"/>
        <MFC max_credits="2M"
             min_threshold="0.4"/>
        <FRAG2 frag_size="60K"  />
        <!--RSVP resend_interval="2000" timeout="10000"/-->
        <pbcast.STATE_TRANSFER/>
    </config>    
  portal-ext.properties: |+ 
    company.default.locale=fi_FI 
    company.default.name=Kuberay
    company.default.time.zone=Europe/Helsinki
    default.admin.screen.name=admin
    default.admin.email.address.prefix=admin
    default.admin.password=asdQWE123@
    default.admin.first.name=Ad
    default.admin.last.name=Min
    cluster.link.enabled=true
    cluster.link.channel.properties.control=/opt/liferay/jgroups-kubernetes.xml
    cluster.link.channel.properties.transport.0=/opt/liferay/jgroups-kubernetes.xml
    cluster.link.autodetect.address={{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local:3306
    jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
    jdbc.default.password=admin 
    jdbc.default.url=jdbc:mysql://{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true 
    jdbc.default.username=root 
    locales=en_US,fi_FI,sv_SE
    locales.beta=
    locales.enabled=en_US,fi_FI,sv_SE
    timezones=Pacific/Midway, Pacific/Honolulu, America/Anchorage, America/Los_Angeles, America/Phoenix, America/Denver, America/Chicago, America/New_York, America/Caracas, America/Puerto_Rico, America/St_Johns, America/Sao_Paulo, America/Noronha, Atlantic/Azores, UTC, Europe/Lisbon, Europe/Paris, Europe/Helsinki, Europe/Istanbul, Asia/Jerusalem, Asia/Baghdad, Asia/Tehran, Asia/Dubai, Asia/Kabul, Asia/Karachi, Asia/Calcutta, Asia/Katmandu, Asia/Dhaka, Asia/Rangoon, Asia/Saigon, Asia/Shanghai, Asia/Tokyo, Asia/Seoul, Australia/Perth, Australia/Eucla, Australia/Darwin, Australia/Sydney, Australia/Lord_Howe, Pacific/Guadalcanal, Pacific/Auckland, Pacific/Enderbury, Pacific/Kiritimati 
    module.framework.auto.deploy.dirs=\
        ${module.framework.configs.dir},\
        ${module.framework.marketplace.dir},\
        ${module.framework.modules.dir},\
        ${module.framework.war.dir}

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-liferay-config