apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ .Release.Name }}-liferay-headless
  name: {{ .Release.Name }}-liferay-headless
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: "jgroups"
    port: 7080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-liferay
    type: portal