apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-liferay
  name: {{ .Release.Name }}-liferay
spec:
  publishNotReadyAddresses: true
  ports:
  - name: "httpslinks"
    port: 8080
    protocol: TCP
  - name: "httplinks"
    port: 8081
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-liferay
    type: portal