apiVersion: v1
kind: Service
metadata:
  labels:
    app: liferay
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: "8080"
    port: 8080
  - name: "8081"
    port: 8081
  selector:
    app: liferay

